AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SIAM SAM Template

Globals:
  Function:
    Timeout: 3

Resources:
  SiamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: handler.handle
      Runtime: python3.8
      Events:
        AddUser:
          Type: Api
          Properties:
            Path: /groups/{group_id}/add-user
            Method: post
        RemoveUser:
          Type: Api
          Properties:
            Path: /groups/{group_id}/remove-user
            Method: post



Outputs:
  SiamApi:
    Description: "API Gateway endpoint URL for Prod stage for Siam function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/groups/"
  SiamFunction:
    Description: "Siam Lambda Function ARN"
    Value: !GetAtt SiamFunction.Arn
  SiamFunctionIamRole:
    Description: "Implicit IAM Role created for Siam function"
    Value: !GetAtt SiamFunctionRole.Arn
